version: "3.7"

services:
  accesslog:
    image: diamol/ch09-access-log
    deploy:
      replicas: 3
  nasa-api:
    image: diamol/ch09-image-gallery
    ports:
      - 8030:80
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: "100M"

n